spring:
  datasource:
    username: system
    password: jmv1500@
    url: jdbc:oracle:thin:@localhost:1521/free
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
